import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { FileText, Download, Calendar, User, CheckCircle, AlertTriangle, Activity, Printer } from 'lucide-react';

const ReportGenerator = ({ equipmentId, analysisData }) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [reportType, setReportType] = useState('full');

  const reportTemplates = {
    full: {
      title: 'Full Maintenance Report',
      sections: ['Executive Summary', 'Current Status', 'Historical Data', 'Recommendations', 'Safety Compliance'],
    },
    summary: {
      title: 'Quick Summary Report',
      sections: ['Status Overview', 'Key Issues', 'Immediate Actions'],
    },
    safety: {
      title: 'Safety Compliance Report',
      sections: ['Safety Audit', 'Compliance Checklist', 'Risk Assessment', 'Corrective Actions'],
    },
  };

  const handleGenerateReport = async () => {
    setIsGenerating(true);
    // Simulate report generation
    setTimeout(() => {
      setIsGenerating(false);
      alert('Report generated successfully! (Demo - In production, this would download a PDF)');
    }, 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    // Create a simple text report for demo
    const reportContent = `
MAINTENANCE WIZARD REPORT
=========================
Equipment: ${equipmentId}
Date: ${new Date().toLocaleDateString()}
Time: ${new Date().toLocaleTimeString()}

STATUS: ${analysisData?.status || 'Critical'}
RISK LEVEL: ${analysisData?.prediction?.risk_score > 50 ? 'High' : 'Medium'}

RECOMMENDATIONS:
${analysisData?.analysis || 'Please run an analysis first.'}

-- Generated by Maintenance Wizard AI
    `;
    
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `maintenance-report-${equipmentId}-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <div className="p-3 bg-gradient-to-br from-green-600 to-emerald-600 rounded-xl">
            <FileText className="text-white w-6 h-6" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-white">Report Generator</h3>
            <p className="text-xs text-slate-400">Create professional maintenance reports</p>
          </div>
        </div>
      </div>

      {/* Report Type Selection */}
      <div className="mb-6">
        <label className="block text-sm font-bold text-slate-400 mb-3 uppercase tracking-wider">
          Report Type
        </label>
        <div className="grid grid-cols-3 gap-3">
          {Object.entries(reportTemplates).map(([key, template]) => (
            <button
              key={key}
              onClick={() => setReportType(key)}
              className={`p-4 rounded-xl border-2 transition-all ${
                reportType === key
                  ? 'border-blue-500 bg-blue-900/30'
                  : 'border-slate-700 bg-slate-800 hover:border-slate-600'
              }`}
            >
              <div className={`font-bold text-sm mb-1 ${reportType === key ? 'text-blue-400' : 'text-slate-300'}`}>
                {template.title.split(' ')[0]}
              </div>
              <div className="text-xs text-slate-500">{template.sections.length} sections</div>
            </button>
          ))}
        </div>
      </div>

      {/* Report Preview */}
      <div className="bg-slate-950 rounded-xl border border-slate-800 p-6 mb-6">
        <div className="border-b border-slate-800 pb-4 mb-4">
          <div className="flex items-center justify-between mb-2">
            <h4 className="text-xl font-bold text-white">{reportTemplates[reportType].title}</h4>
            <div className="flex items-center gap-2 text-sm text-slate-400">
              <Calendar className="w-4 h-4" />
              {new Date().toLocaleDateString()}
            </div>
          </div>
          <div className="flex items-center gap-4 text-sm">
            <span className="flex items-center gap-1 text-slate-400">
              <User className="w-4 h-4" />
              Maintenance Wizard AI
            </span>
            <span className="flex items-center gap-1 text-slate-400">
              <Activity className="w-4 h-4" />
              {equipmentId}
            </span>
          </div>
        </div>

        <div className="space-y-4">
          {reportTemplates[reportType].sections.map((section, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1 }}
              className="p-4 bg-slate-900/50 rounded-lg border border-slate-800"
            >
              <h5 className="font-bold text-white mb-2 flex items-center gap-2">
                {index % 2 === 0 ? (
                  <CheckCircle className="w-4 h-4 text-green-500" />
                ) : (
                  <AlertTriangle className="w-4 h-4 text-orange-500" />
                )}
                {section}
              </h5>
              <p className="text-sm text-slate-400">
                {section === 'Executive Summary' && 'This report provides a comprehensive analysis of the current equipment status and recommended maintenance actions.'}
                {section === 'Current Status' && `Equipment ${equipmentId} is currently experiencing anomalies in the cooling system. Temperature readings are elevated by ${analysisData?.prediction?.risk_score || '15'}%.`}
                {section === 'Historical Data' && 'Reviewing past 6 months of maintenance records shows similar issues occurring approximately every 8 weeks.'}
                {section === 'Recommendations' && 'Schedule immediate descaling procedure, followed by a full system inspection. Consider implementing a preventive maintenance schedule.'}
                {section === 'Safety Compliance' && 'All recommended actions comply with OSHA standards and internal safety protocols. PPE and LOTO procedures are mandatory.'}
                {section === 'Status Overview' && 'Overall equipment status: Critical - Immediate attention required.'}
                {section === 'Key Issues' && '1) Elevated cooling temperatures 2) Reduced flow rate 3) Potential scale buildup'}
                {section === 'Immediate Actions' && '1) Reduce load 2) Schedule maintenance 3) Monitor closely'}
                {section === 'Safety Audit' && 'Safety protocols are in place and documented. Team training is up to date.'}
                {section === 'Compliance Checklist' && '[✓] PPE available [✓] LOTO procedures [✓] Training records [✓] Emergency contacts'}
                {section === 'Risk Assessment' && 'Current risk level: Medium-High. Failure to act may result in unplanned downtime.'}
                {section === 'Corrective Actions' && 'All maintenance tasks must follow standard operating procedures and safety guidelines.'}
              </p>
            </motion.div>
          ))}
        </div>
      </div>

      {/* Actions */}
      <div className="flex gap-3">
        <button
          onClick={handleGenerateReport}
          disabled={isGenerating}
          className="flex-1 bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 disabled:opacity-50 disabled:cursor-not-allowed text-white font-bold py-3 px-6 rounded-xl transition-all flex items-center justify-center gap-2"
        >
          {isGenerating ? (
            <>
              <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <FileText className="w-5 h-5" />
              Generate Report
            </>
          )}
        </button>
        <button
          onClick={handleDownload}
          className="bg-slate-700 hover:bg-slate-600 text-white font-bold py-3 px-6 rounded-xl transition-all flex items-center justify-center gap-2"
        >
          <Download className="w-5 h-5" />
        </button>
        <button
          onClick={handlePrint}
          className="bg-slate-700 hover:bg-slate-600 text-white font-bold py-3 px-6 rounded-xl transition-all flex items-center justify-center gap-2"
        >
          <Printer className="w-5 h-5" />
        </button>
      </div>
    </div>
  );
};

export default ReportGenerator;
