import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { FileText, Download, Printer, Plus, Trash2, Wrench, User, Calendar, CheckCircle } from 'lucide-react';

export default function WorkOrderGenerator({ selectedEq }) {
  const [workOrders, setWorkOrders] = useState([
    { id: 'WO-2026-001', equipment: 'BF-01', type: 'Emergency', title: 'Cooling System Descaling', description: 'Urgent descaling needed due to temperature spike', status: 'In Progress', priority: 'High', assignee: 'John Smith', date: '2026-06-14' },
    { id: 'WO-2026-002', equipment: 'BF-02', type: 'Preventive', title: 'Monthly Inspection', description: 'Routine maintenance check', status: 'Completed', priority: 'Medium', assignee: 'Sarah Johnson', date: '2026-06-10' },
  ]);
  const [newOrder, setNewOrder] = useState({
    equipment: selectedEq,
    type: 'Preventive',
    title: '',
    description: '',
    priority: 'Medium',
    assignee: '',
    dueDate: '',
  });

  const handleCreateOrder = () => {
    if (newOrder.title) {
      const id = `WO-2026-${String(workOrders.length + 1).padStart(3, '0')}`;
      setWorkOrders([{ ...newOrder, id, status: 'New', date: new Date().toISOString().split('T')[0] }, ...workOrders]);
      setNewOrder({
        equipment: selectedEq,
        type: 'Preventive',
        title: '',
        description: '',
        priority: 'Medium',
        assignee: '',
        dueDate: '',
      });
    }
  };

  const handleDownload = (order) => {
    const content = `
WORK ORDER ${order.id}
==============
Equipment: ${order.equipment}
Type: ${order.type}
Title: ${order.title}
Priority: ${order.priority}
Assignee: ${order.assignee}
Date: ${order.date}
Status: ${order.status}

DESCRIPTION:
${order.description || 'No description provided'}
==============
Generated by Maintenance Wizard
    `;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${order.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h3 className="text-lg font-bold text-white flex items-center gap-2">
            <FileText className="w-5 h-5 text-green-400" />
            Work Order Generator
          </h3>
          <p className="text-sm text-slate-400">Create and manage maintenance work orders</p>
        </div>
        <div className="flex gap-2">
          <button className="p-2 bg-slate-800 hover:bg-slate-700 rounded-lg transition-colors">
            <Printer className="w-5 h-5 text-slate-300" />
          </button>
        </div>
      </div>

      {/* Create New Work Order */}
      <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-4 mb-6">
        <h4 className="font-bold text-slate-200 mb-4 flex items-center gap-2">
          <Plus className="w-4 h-4 text-blue-400" />
          Create New Work Order
        </h4>
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          <div>
            <label className="block text-xs font-bold text-slate-400 mb-1">Equipment</label>
            <select
              value={newOrder.equipment}
              onChange={(e) => setNewOrder({ ...newOrder, equipment: e.target.value })}
              className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-slate-200"
            >
              <option>BF-01</option>
              <option>BF-02</option>
              <option>BF-03</option>
              <option>BF-04</option>
              <option>BF-05</option>
            </select>
          </div>
          <div>
            <label className="block text-xs font-bold text-slate-400 mb-1">Type</label>
            <select
              value={newOrder.type}
              onChange={(e) => setNewOrder({ ...newOrder, type: e.target.value })}
              className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-slate-200"
            >
              <option>Preventive</option>
              <option>Corrective</option>
              <option>Emergency</option>
              <option>Predictive</option>
            </select>
          </div>
          <div>
            <label className="block text-xs font-bold text-slate-400 mb-1">Title</label>
            <input
              type="text"
              value={newOrder.title}
              onChange={(e) => setNewOrder({ ...newOrder, title: e.target.value })}
              className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-slate-200"
              placeholder="Enter work order title..."
            />
          </div>
          <div>
            <label className="block text-xs font-bold text-slate-400 mb-1">Priority</label>
            <select
              value={newOrder.priority}
              onChange={(e) => setNewOrder({ ...newOrder, priority: e.target.value })}
              className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-slate-200"
            >
              <option>Low</option>
              <option>Medium</option>
              <option>High</option>
              <option>Critical</option>
            </select>
          </div>
          <div>
            <label className="block text-xs font-bold text-slate-400 mb-1">Assignee</label>
            <input
              type="text"
              value={newOrder.assignee}
              onChange={(e) => setNewOrder({ ...newOrder, assignee: e.target.value })}
              className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-slate-200"
              placeholder="Enter assignee name..."
            />
          </div>
          <div>
            <label className="block text-xs font-bold text-slate-400 mb-1">Due Date</label>
            <input
              type="date"
              value={newOrder.dueDate}
              onChange={(e) => setNewOrder({ ...newOrder, dueDate: e.target.value })}
              className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-slate-200"
            />
          </div>
          <div className="lg:col-span-2">
            <label className="block text-xs font-bold text-slate-400 mb-1">Description</label>
            <textarea
              value={newOrder.description}
              onChange={(e) => setNewOrder({ ...newOrder, description: e.target.value })}
              className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-slate-200"
              placeholder="Describe the work to be performed..."
              rows="3"
            />
          </div>
        </div>
        <button
          onClick={handleCreateOrder}
          disabled={!newOrder.title}
          className="mt-4 w-full bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 disabled:opacity-50 text-white font-bold py-3 px-4 rounded-lg transition-all flex items-center justify-center gap-2"
        >
          <Plus className="w-5 h-5" />
          Create Work Order
        </button>
      </div>

      {/* Work Orders List */}
      <div className="space-y-3">
        {workOrders.map((order, index) => (
          <motion.div
            key={order.id}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.1 }}
            className="p-4 bg-slate-800/50 border border-slate-700 rounded-xl"
          >
            <div className="flex items-start justify-between">
              <div className="flex items-center gap-3">
                <div className={`p-2 rounded-lg ${
                  order.priority === 'High' || order.priority === 'Critical' ? 'bg-red-900/50' :
                  order.priority === 'Medium' ? 'bg-amber-900/50' : 'bg-green-900/50'
                }`}>
                  <Wrench className={`w-4 h-4 ${
                    order.priority === 'High' || order.priority === 'Critical' ? 'text-red-400' :
                    order.priority === 'Medium' ? 'text-amber-400' : 'text-green-400'
                  }`} />
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <h4 className="font-bold text-slate-200">{order.title}</h4>
                    <span className={`text-xs font-bold px-2 py-0.5 rounded-full bg-slate-700 text-slate-300`}>
                      {order.id}
                    </span>
                  </div>
                  <div className="text-sm text-slate-400 flex items-center gap-4">
                    <span className="flex items-center gap-1">
                      <Wrench className="w-3 h-3" />
                      {order.equipment}
                    </span>
                    <span className="flex items-center gap-1">
                      <User className="w-3 h-3" />
                      {order.assignee}
                    </span>
                    <span className="flex items-center gap-1">
                      <Calendar className="w-3 h-3" />
                      {order.date}
                    </span>
                  </div>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <span className={`text-xs font-bold px-3 py-1 rounded-full mr-2`} style={{
                  backgroundColor: order.status === 'Completed' ? 'rgba(34,197,94,0.2)' :
                  order.status === 'In Progress' ? 'rgba(59,130,246,0.2)' :
                  'rgba(100,116,139,0.2)',
                  color: order.status === 'Completed' ? '#22c55e' :
                  order.status === 'In Progress' ? '#3b82f6' : '#64748b'
                }}>
                  {order.status}
                </span>
                <button
                  onClick={() => handleDownload(order)}
                  className="p-2 bg-slate-700 hover:bg-slate-600 rounded-lg transition-colors"
                >
                  <Download className="w-4 h-4 text-slate-300" />
                </button>
              </div>
            </div>
            <div className="flex items-center gap-2 mt-3">
              {order.status === 'Completed' ? (
                <CheckCircle className="w-4 h-4 text-green-400" />
              ) : (
                <div className="flex-1 h-1 bg-slate-700 rounded-full overflow-hidden">
                  <div className="h-full bg-blue-500" style={{ width: order.status === 'In Progress' ? '60%' : '10%' }} />
                </div>
              )}
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
